{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "vscode": {
     "languageId": "javascript"
    }
   },
   "outputs": [],
   "source": [
    "$(document).ready(function () {\n",
    "    // Initialize the WOW plugin\n",
    "    new WOW().init();\n",
    "\n",
    "    // Parallax effect for the banner\n",
    "    function parallax() {\n",
    "        const posY = window.pageYOffset;\n",
    "        const image = document.getElementById(\"parallax\");\n",
    "        image.style.top = posY * 0.9 + \"px\";\n",
    "    }\n",
    "\n",
    "    window.addEventListener(\"scroll\", parallax);\n",
    "\n",
    "    // Define a function to generate book elements\n",
    "    function generateBookElement(book) {\n",
    "        return `\n",
    "            <div class=\"col-md-4 col-sm-6 col-xs-12\">\n",
    "                <a href=\"${book.link}\" target=\"_blank\">\n",
    "                    <div class=\"block\">\n",
    "                        <div class=\"works-thumb\" style=\"background-image: url(${book.imageLink})\"></div>\n",
    "                        <div class=\"works-caption\">${book.bookName}</div>\n",
    "                    </div>\n",
    "                </a>\n",
    "            </div>\n",
    "        `;\n",
    "    }\n",
    "\n",
    "    // Populate the books section\n",
    "    function generateBooks(books) {\n",
    "        const container = document.querySelector(\"#works .container\");\n",
    "        const html = books.map(generateBookElement).join('');\n",
    "\n",
    "        container.innerHTML = html;\n",
    "    }\n",
    "\n",
    "    // Usage\n",
    "    const books = [\n",
    "        {\n",
    "            imageLink: \"https://www.takewalks.com/blog/wp-content/uploads/2013/05/gatsby.jpg\",\n",
    "            bookName: \"The Great Gatsby!\",\n",
    "            link: \"https://example.com/great-gatsby\",\n",
    "        },\n",
    "        // ... (other book objects)\n",
    "    ];\n",
    "\n",
    "    // Wait for the DOM to be fully loaded\n",
    "    window.addEventListener(\"DOMContentLoaded\", (event) => {\n",
    "        generateBooks(books);\n",
    "    });\n",
    "});"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "toc: true\n",
    "comments: true\n",
    "layout: post\n",
    "title: Project Documentation - Amazon Book Catalog\n",
    "description: A catalog dedicated to extending text of books on Amazon and finding their details.\n",
    "type: tangibles\n",
    "courses: {compsci: {week: 10} }\n",
    "---\n",
    "\n",
    "## Introduction\n",
    "These are our many key parts to managing and finishing our project.\n",
    "\n",
    "1. [README.md](https://github.com/AdityaSamavedam/FinalFrontend/blob/main/README.md). \n",
    "This is the repo that we are using for the Frontend of our API. \n",
    "\n",
    "2. [Project Plan](https://github.com/AdityaSamavedam/FinalFrontend). This is the link for our project plan. We started off with a language model able to speak Shakespeare. But it didn't seem to give the users a purpose so we then switched to a text extender which extends text from books on an Amazon Book Catalog we made. It also gives us the main story of the book which helps users know whether they want to get this book from Amazon or not.\n",
    "\n",
    "3. [Issue Management](https://github.com/AdityaSamavedam/FinalFrontend/issues). This link is for the issues on our Github page. The site will tell you if any issues have been closed.\n",
    "\n",
    "4. [GitHub Pages Blog](https://jm1021.github.io/alienWorld/blogs/).  A big advantage of GitHub Pages as a frontend is that allows for classic frontend runtime and blogging to be contained in one place.  In education, a huge part of our project is how it was made, and how we collaborated, and how we progressed through steps.\n",
    "\n",
    "5. [GitHub Pages History/Time Box](https://jm1021.github.io/alienWorld/compsci/). \n",
    " ## October 4: \n",
    " We talked about what we will do for the Passion Project. We brainstormed ideas about team selection and which person will work on what.\n",
    " ## October 7-8:\n",
    " We started work on the Passion Project. Initially, we decided to make a website about a Shakespeare AI language model and created a video showing our ideas.\n",
    " ## October 9:\n",
    " Our team presented the Passion Project to Mr. Mortenson. Based on his feedback, we realized that this idea did not provide a benefit to the user and we will have to change it.\n",
    " ## October 9-12:\n",
    " We worked on creating our iteration lesson and adding homework codes and hacks.\n",
    " ## October 16th:\n",
    " We changed our Passion Project to a text extender called the Amazon Book Catalog. This would help users easily find books on Amazon and with just a few lines of text from a book, get summaries of books to see if they should spend time and money on buying and reading the book.\n",
    " \n",
    "\n",
    "6. [Anatomy of Amazon Book Catalog](https://github.com/AdityaSamavedam/FinalFrontend).  This shows all the code that was made to make the Catalog. \n",
    "7. Code Comments.  Almost everyone, including Teachers, do not remember how code works without comments.  Be sure to comment key code block and algorithms.\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
